[
    {
        "imgSrc": "https://i.ibb.co/FqqqKck/view9.webp",
        "location": "Cape Town, South Africa",
        "checkIn": "2023-09-01",
        "checkOut": "2023-09-02",
        "locationDecs": "9,965 kilometers away",
        "price": 10,
        "rating": 4.5,
        "placeType": "any",
        "propertyType": "House",
        "beds": 3,
        "bedrooms": 3,
        "bathrooms": 3,
        "guestCapacity": 15,
        "featureCategory": "Amazing pools"
    },
    {
        "imgSrc": "https://i.ibb.co/n6MjMXT/view10.webp",
        "location": "Madrid, Spain",
        "checkIn": "2023-09-02",
        "checkOut": "2023-09-03",
        "locationDecs": "8,864 kilometers away",
        "price": 15,
        "rating": 4.5,
        "placeType": "any",
        "propertyType": "House",
        "beds": 2,
        "bedrooms": 2,
        "bathrooms": 2,
        "guestCapacity": 15,
        "featureCategory": "Amazing pools"
    },
    {
        "imgSrc": "https://i.ibb.co/gSxwXXq/view11.webp",
        "location": "Docklands, Australia",
        "checkIn": "2023-09-03",
        "checkOut": "2023-09-04",
        "locationDecs": "8,688 kilometers away",
        "price": 20,
        "rating": 4.5,
        "placeType": "any",
        "propertyType": "House",
        "beds": 3,
        "bedrooms": 3,
        "bathrooms": 3,
        "guestCapacity": 15,
        "featureCategory": "Amazing pools"
    },
    {
        "imgSrc": "https://i.ibb.co/K6SXNzc/view12.webp",
        "location": "Carlton, Australia",
        "checkIn": "2023-09-05",
        "checkOut": "2023-09-06",
        "locationDecs": "8,688 kilometers away",
        "price": 25,
        "rating": 4.5,
        "placeType": "any",
        "propertyType": "House",
        "beds": 4,
        "bedrooms": 4,
        "bathrooms": 4,
        "guestCapacity": 15,
        "featureCategory": "Amazing pools"
    },
    {
        "imgSrc": "https://i.ibb.co/NS9DsQh/view13.webp",
        "location": "Cape Town, South Africa",
        "checkIn": "2023-09-07",
        "checkOut": "2023-09-08",
        "locationDecs": "9,963 kilometers away",
        "price": 30,
        "rating": 4.5,
        "placeType": "any",
        "propertyType": "House",
        "beds": 3,
        "bedrooms": 3,
        "bathrooms": 3,
        "guestCapacity": 15,
        "featureCategory": "Amazing pools"
    },
    {
        "imgSrc": "https://i.ibb.co/m0fVYwW/view14.webp",
        "location": "Cape Town, South Africa",
        "checkIn": "2023-09-06",
        "checkOut": "2023-09-08",
        "locationDecs": "9,962 kilometers away",
        "price": 35,
        "rating": 4.5,
        "placeType": "any",
        "propertyType": "House",
        "beds": 8,
        "bedrooms": 4,
        "bathrooms": 2,
        "guestCapacity": 15,
        "featureCategory": "Lakefront"
    },
    {
        "imgSrc": "https://i.ibb.co/RHhCQ4W/view15.webp",
        "location": "Dubai, UAE",
        "checkIn": "2023-09-09",
        "checkOut": "2023-09-10",
        "locationDecs": "3,738 kilometers away",
        "price": 40,
        "rating": 4.5,
        "placeType": "any",
        "propertyType": "House",
        "beds": 6,
        "bedrooms": 3,
        "bathrooms": 2,
        "guestCapacity": 15,
        "featureCategory": "Lakefront"
    },
    {
        "imgSrc": "https://i.ibb.co/WKBx2wW/view16.webp",
        "location": "Florence, Italy",
        "checkIn": "2023-09-12",
        "checkOut": "2023-09-13",
        "locationDecs": "7,578 kilometers away",
        "price": 45,
        "rating": 4.5,
        "placeType": "any",
        "propertyType": "House",
        "beds": 5,
        "bedrooms": 2,
        "bathrooms": 2,
        "guestCapacity": 15,
        "featureCategory": "Lakefront"
    },
    {
        "imgSrc": "https://i.ibb.co/61QP7fJ/view17.webp",
        "location": "Istanbul, Turkey",
        "checkIn": "2023-09-12",
        "checkOut": "2023-09-14",
        "locationDecs": "6,160 kilometers away",
        "price": 50,
        "rating": 4.5,
        "placeType": "any",
        "propertyType": "Apartment",
        "beds": 5,
        "bedrooms": 6,
        "bathrooms": 7,
        "guestCapacity": 15,
        "featureCategory": "Lakefront"
    },
    {
        "imgSrc": "https://i.ibb.co/z4w40hS/view18.webp",
        "location": "Paris, France",
        "checkIn": "2023-09-13",
        "checkOut": "2023-09-15",
        "locationDecs": "8,126 kilometers away",
        "price": 55,
        "rating": 4.5,
        "placeType": "any",
        "propertyType": "Apartment",
        "beds": 7,
        "bedrooms": 6,
        "bathrooms": 4,
        "guestCapacity": 15,
        "featureCategory": "Lakefront"
    },
    {
        "imgSrc": "https://i.ibb.co/ZxtWTsq/view19.webp",
        "location": "Dubai, UAE",
        "checkIn": "2023-09-14",
        "checkOut": "2023-09-16",
        "locationDecs": "3,737 kilometers away",
        "price": 60,
        "rating": 4.5,
        "placeType": "room",
        "propertyType": "Apartment",
        "beds": 2,
        "bedrooms": 4,
        "bathrooms": 3,
        "guestCapacity": 15,
        "featureCategory": "Surfing"
    },
    {
        "imgSrc": "https://i.ibb.co/6Pj3h8r/view20.webp",
        "location": "Bondi Beach, Australia",
        "checkIn": "2023-09-15",
        "checkOut": "2023-09-17",
        "locationDecs": "8,864 kilometers away",
        "price": 65,
        "rating": 4.5,
        "placeType": "room",
        "propertyType": "Apartment",
        "beds": 6,
        "bedrooms": 4,
        "bathrooms": 5,
        "guestCapacity": 15,
        "featureCategory": "Surfing"
    },
    {
        "imgSrc": "https://i.ibb.co/pZGCJXp/view21.webp",
        "location": "Madrid, Spain",
        "checkIn": "2023-09-17",
        "checkOut": "2023-09-18",
        "locationDecs": "8,865 kilometers away",
        "price": 70,
        "rating": 4.5,
        "placeType": "room",
        "propertyType": "Apartment",
        "beds": 5,
        "bedrooms": 3,
        "bathrooms": 4,
        "guestCapacity": 15,
        "featureCategory": "Surfing"
    },
    {
        "imgSrc": "https://i.ibb.co/YkXDXGY/view22.webp",
        "location": "Athina, Greece",
        "checkIn": "2023-09-18",
        "checkOut": "2023-09-19",
        "locationDecs": "6,629 kilometers away",
        "price": 75,
        "rating": 4.5,
        "placeType": "room",
        "propertyType": "Apartment",
        "beds": 4,
        "bedrooms": 5,
        "bathrooms": 8,
        "guestCapacity": 15,
        "featureCategory": "Surfing"
    },
    {
        "imgSrc": "https://i.ibb.co/28Xhw6T/view23.webp",
        "location": "Marrakesh, Morocco",
        "checkIn": "2023-09-19",
        "checkOut": "2023-09-21",
        "locationDecs": "9,594 kilometers away",
        "price": 80,
        "rating": 4.5,
        "placeType": "room",
        "propertyType": "Apartment",
        "beds": 6,
        "bedrooms": 7,
        "bathrooms": 5,
        "guestCapacity": 15,
        "featureCategory": "Surfing"
    },
    {
        "imgSrc": "https://i.ibb.co/3Mkjp69/view24.webp",
        "location": "Carlton, Australia",
        "checkIn": "2023-09-18",
        "checkOut": "2023-09-22",
        "locationDecs": "8,688 kilometers away",
        "price": 85,
        "rating": 4.5,
        "placeType": "room",
        "propertyType": "Apartment",
        "beds": 7,
        "bedrooms": 6,
        "bathrooms": 5,
        "guestCapacity": 15,
        "featureCategory": "Farms"
    },
    {
        "imgSrc": "https://i.ibb.co/P6SFW96/view25.webp",
        "location": "Sydney, Australia",
        "checkIn": "2023-09-20",
        "checkOut": "2023-09-22",
        "locationDecs": "8,858 kilometers away",
        "price": 90,
        "rating": 4.5,
        "placeType": "room",
        "propertyType": "Guesthouse",
        "beds": 6,
        "bedrooms": 5,
        "bathrooms": 6,
        "guestCapacity": 15,
        "featureCategory": "Farms"
    },
    {
        "imgSrc": "https://i.ibb.co/PcrQZwW/view26.webp",
        "location": "Seoul, South Korea",
        "checkIn": " 2023-09-23",
        "checkOut": "2023-09-24",
        "locationDecs": "3,750 kilometers away",
        "price": 100,
        "rating": 4.5,
        "placeType": "room",
        "propertyType": "Guesthouse",
        "beds": 5,
        "bedrooms": 6,
        "bathrooms": 5,
        "guestCapacity": 15,
        "featureCategory": "Farms"
    },
    {
        "imgSrc": "https://i.ibb.co/VgPwG4b/view27.webp",
        "location": "Mumbai, India",
        "checkIn": "2023-09-24",
        "checkOut": "2023-09-26",
        "locationDecs": "2,007 kilometers away",
        "price": 110,
        "rating": 4.5,
        "placeType": "room",
        "propertyType": "Guesthouse",
        "beds": 8,
        "bedrooms": 7,
        "bathrooms": 6,
        "guestCapacity": 15,
        "featureCategory": "Farms"
    },
    {
        "imgSrc": "https://i.ibb.co/T8STpzt/view28.webp",
        "location": "Ubud, Indonesia",
        "checkIn": "2023-09-26",
        "checkOut": "2023-09-28",
        "locationDecs": "4,277 kilometers away",
        "price": 120,
        "rating": 4.5,
        "placeType": "room",
        "propertyType": "Guesthouse",
        "beds": 7,
        "bedrooms": 4,
        "bathrooms": 7,
        "guestCapacity": 15,
        "featureCategory": "Farms"
    },
    {
        "imgSrc": "https://i.ibb.co/qW5Hnp6/view29.webp",
        "location": "Rome, Italy",
        "checkIn": "2023-09-25",
        "checkOut": "2023-09-27",
        "locationDecs": "7,522 kilometers away",
        "price": 125,
        "rating": 4.5,
        "placeType": "entire room",
        "propertyType": "Guesthouse",
        "beds": 6,
        "bedrooms": 6,
        "bathrooms": 6,
        "guestCapacity": 15,
        "featureCategory": "Top of the world"
    },
    {
        "imgSrc": "https://i.ibb.co/0Krj9GB/view30.webp",
        "location": "Lisbon, Portugal",
        "checkIn": "2023-09-28",
        "checkOut": "2023-09-29",
        "locationDecs": "9,367 kilometers away",
        "price": 115,
        "rating": 4.5,
        "placeType": "entire room",
        "propertyType": "Guesthouse",
        "beds": 5,
        "bedrooms": 5,
        "bathrooms": 5,
        "guestCapacity": 15,
        "featureCategory": "Top of the world"
    },
    {
        "imgSrc": "https://i.ibb.co/hCWkk8p/view3.jpg",
        "location": "Melbourne, Australia",
        "checkIn": "2023-09-28",
        "checkOut": "2023-09-30",
        "locationDecs": "8,688 kilometers away",
        "price": 130,
        "rating": 4.5,
        "placeType": "entire room",
        "propertyType": "Hotel",
        "beds": 6,
        "bedrooms": 6,
        "bathrooms": 6,
        "guestCapacity": 15,
        "featureCategory": "Top of the world"
    },
    {
        "imgSrc": "https://i.ibb.co/zscZYSp/view2.jpg",
        "location": "Kuala Lumpur, Malaysia",
        "checkIn": "2023-09-05",
        "checkOut": "2023-09-08",
        "locationDecs": "2,383 kilometers away",
        "price": 105,
        "rating": 4.5,
        "placeType": "entire room",
        "propertyType": "Hotel",
        "beds": 7,
        "bedrooms": 7,
        "bathrooms": 7,
        "guestCapacity": 15,
        "featureCategory": "Top of the world"
    },
    {
        "imgSrc": "https://i.ibb.co/3vGCLD3/view1.webp",
        "location": "Rome, Italy",
        "checkIn": "2023-09-10",
        "checkOut": "2023-09-14",
        "locationDecs": "7,517 kilometers away",
        "price": 135,
        "rating": 4.5,
        "placeType": "entire room",
        "propertyType": "Hotel",
        "beds": 5,
        "bedrooms": 5,
        "bathrooms": 5,
        "guestCapacity": 15,
        "featureCategory": "Top of the world"
    },
    {
        "imgSrc": "https://i.ibb.co/02hMSTP/view4.webp",
        "location": "Paris, France",
        "checkIn": "2023-09-15",
        "checkOut": "2023-09-20",
        "locationDecs": "8,126 kilometers away",
        "price": 145,
        "rating": 4.5,
        "placeType": "entire room",
        "propertyType": "Hotel",
        "beds": 8,
        "bedrooms": 8,
        "bathrooms": 8,
        "guestCapacity": 15,
        "featureCategory": "Amazing"
    },
    {
        "imgSrc": "https://i.ibb.co/qWNB7Hj/view5.webp",
        "location": "London, UK",
        "checkIn": "2023-09-20",
        "checkOut": "2023-09-25",
        "locationDecs": "8,205 kilometers away",
        "price": 140,
        "rating": 4.5,
        "placeType": "entire room",
        "propertyType": "Hotel",
        "beds": 8,
        "bedrooms": 8,
        "bathrooms": 8,
        "guestCapacity": 15,
        "featureCategory": "Amazing"
    },
    {
        "imgSrc": "https://i.ibb.co/V2PN6kd/view6.webp",
        "location": "Split, Croatia",
        "checkIn": "2023-09-25",
        "checkOut": "2023-09-30",
        "locationDecs": "7,170 kilometers away",
        "price": 35,
        "rating": 4.5,
        "placeType": "entire room",
        "propertyType": "Hotel",
        "beds": 7,
        "bedrooms": 7,
        "bathrooms": 7,
        "guestCapacity": 15,
        "featureCategory": "Amazing"
    },
    {
        "imgSrc": "https://i.ibb.co/dGY7824/view7.webp",
        "location": "Bondi Beach, Australia",
        "checkIn": "2023-09-12",
        "checkOut": "2023-09-16",
        "locationDecs": "8,864 kilometers away",
        "price": 45,
        "rating": 4.5,
        "placeType": "entire room",
        "propertyType": "Hotel",
        "beds": 6,
        "bedrooms": 6,
        "bathrooms": 6,
        "guestCapacity": 15,
        "featureCategory": "Amazing"
    },
    {
        "imgSrc": "https://i.ibb.co/ZG7wQxn/view8.webp",
        "location": "Cape Town, South Africa",
        "checkIn": "2023-09-16",
        "checkOut": "2023-09-21",
        "locationDecs": "9,963 kilometers away",
        "price": 55,
        "rating": 4.5,
        "placeType": "entire room",
        "propertyType": "Hotel",
        "beds": 5,
        "bedrooms": 5,
        "bathrooms": 5,
        "guestCapacity": 15,
        "featureCategory": "Amazing"
    }
]


const query = [
    {
        "imgSrc": "https://i.ibb.co/FqqqKck/view9.webp",
        "location": "Cape Town, South Africa",
        "checkIn": new Date("2023-09-01"),
        "checkOut": new Date("2023-09-02"),
        "locationDecs": "9,965 kilometers away",
        "price": 10,
        "rating": 4.5,
        "placeType": "any",
        "propertyType": "House",
        "beds": 3,
        "bedrooms": 3,
        "bathrooms": 3,
        "guestCapacity": 15,
        "featureCategory": "Amazing pools"
    },
    {
        "imgSrc": "https://i.ibb.co/n6MjMXT/view10.webp",
        "location": "Madrid, Spain",
        "checkIn": new Date("2023-09-02"),
        "checkOut": new Date("2023-09-03"),
        "locationDecs": "8,864 kilometers away",
        "price": 15,
        "rating": 4.5,
        "placeType": "any",
        "propertyType": "House",
        "beds": 2,
        "bedrooms": 2,
        "bathrooms": 2,
        "guestCapacity": 15,
        "featureCategory": "Amazing pools"
    },
    {
        "imgSrc": "https://i.ibb.co/gSxwXXq/view11.webp",
        "location": "Docklands, Australia",
        "checkIn": new Date("2023-09-03"),
        "checkOut": new Date("2023-09-04"),
        "locationDecs": "8,688 kilometers away",
        "price": 20,
        "rating": 4.5,
        "placeType": "any",
        "propertyType": "House",
        "beds": 3,
        "bedrooms": 3,
        "bathrooms": 3,
        "guestCapacity": 15,
        "featureCategory": "Amazing pools"
    },
    {
        "imgSrc": "https://i.ibb.co/K6SXNzc/view12.webp",
        "location": "Carlton, Australia",
        "checkIn": new Date("2023-09-05"),
        "checkOut": new Date("2023-09-06"),
        "locationDecs": "8,688 kilometers away",
        "price": 25,
        "rating": 4.5,
        "placeType": "any",
        "propertyType": "House",
        "beds": 4,
        "bedrooms": 4,
        "bathrooms": 4,
        "guestCapacity": 15,
        "featureCategory": "Amazing pools"
    },
    {
        "imgSrc": "https://i.ibb.co/NS9DsQh/view13.webp",
        "location": "Cape Town, South Africa",
        "checkIn": new Date("2023-09-07"),
        "checkOut": new Date("2023-09-08"),
        "locationDecs": "9,963 kilometers away",
        "price": 30,
        "rating": 4.5,
        "placeType": "any",
        "propertyType": "House",
        "beds": 3,
        "bedrooms": 3,
        "bathrooms": 3,
        "guestCapacity": 15,
        "featureCategory": "Amazing pools"
    },
    {
        "imgSrc": "https://i.ibb.co/m0fVYwW/view14.webp",
        "location": "Cape Town, South Africa",
        "checkIn": new Date("2023-09-06"),
        "checkOut": new Date("2023-09-08"),
        "locationDecs": "9,962 kilometers away",
        "price": 35,
        "rating": 4.5,
        "placeType": "any",
        "propertyType": "House",
        "beds": 8,
        "bedrooms": 4,
        "bathrooms": 2,
        "guestCapacity": 15,
        "featureCategory": "Lakefront"
    },
    {
        "imgSrc": "https://i.ibb.co/RHhCQ4W/view15.webp",
        "location": "Dubai, UAE",
        "checkIn": new Date("2023-09-09"),
        "checkOut": new Date("2023-09-10"),
        "locationDecs": "3,738 kilometers away",
        "price": 40,
        "rating": 4.5,
        "placeType": "any",
        "propertyType": "House",
        "beds": 6,
        "bedrooms": 3,
        "bathrooms": 2,
        "guestCapacity": 15,
        "featureCategory": "Lakefront"
    },
    {
        "imgSrc": "https://i.ibb.co/WKBx2wW/view16.webp",
        "location": "Florence, Italy",
        "checkIn": new Date("2023-09-12"),
        "checkOut": new Date("2023-09-13"),
        "locationDecs": "7,578 kilometers away",
        "price": 45,
        "rating": 4.5,
        "placeType": "any",
        "propertyType": "House",
        "beds": 5,
        "bedrooms": 2,
        "bathrooms": 2,
        "guestCapacity": 15,
        "featureCategory": "Lakefront"
    },
    {
        "imgSrc": "https://i.ibb.co/61QP7fJ/view17.webp",
        "location": "Istanbul, Turkey",
        "checkIn": new Date("2023-09-12"),
        "checkOut": new Date("2023-09-14"),
        "locationDecs": "6,160 kilometers away",
        "price": 50,
        "rating": 4.5,
        "placeType": "any",
        "propertyType": "Apartment",
        "beds": 5,
        "bedrooms": 6,
        "bathrooms": 7,
        "guestCapacity": 15,
        "featureCategory": "Lakefront"
    },
    {
        "imgSrc": "https://i.ibb.co/z4w40hS/view18.webp",
        "location": "Paris, France",
        "checkIn": new Date("2023-09-13"),
        "checkOut": new Date("2023-09-15"),
        "locationDecs": "8,126 kilometers away",
        "price": 55,
        "rating": 4.5,
        "placeType": "any",
        "propertyType": "Apartment",
        "beds": 7,
        "bedrooms": 6,
        "bathrooms": 4,
        "guestCapacity": 15,
        "featureCategory": "Lakefront"
    },
    {
        "imgSrc": "https://i.ibb.co/ZxtWTsq/view19.webp",
        "location": "Dubai, UAE",
        "checkIn": new Date("2023-09-14"),
        "checkOut": new Date("2023-09-16"),
        "locationDecs": "3,737 kilometers away",
        "price": 60,
        "rating": 4.5,
        "placeType": "room",
        "propertyType": "Apartment",
        "beds": 2,
        "bedrooms": 4,
        "bathrooms": 3,
        "guestCapacity": 15,
        "featureCategory": "Surfing"
    },
    {
        "imgSrc": "https://i.ibb.co/6Pj3h8r/view20.webp",
        "location": "Bondi Beach, Australia",
        "checkIn": new Date("2023-09-15"),
        "checkOut": new Date("2023-09-17"),
        "locationDecs": "8,864 kilometers away",
        "price": 65,
        "rating": 4.5,
        "placeType": "room",
        "propertyType": "Apartment",
        "beds": 6,
        "bedrooms": 4,
        "bathrooms": 5,
        "guestCapacity": 15,
        "featureCategory": "Surfing"
    },
    {
        "imgSrc": "https://i.ibb.co/pZGCJXp/view21.webp",
        "location": "Madrid, Spain",
        "checkIn": new Date("2023-09-17"),
        "checkOut": new Date("2023-09-18"),
        "locationDecs": "8,865 kilometers away",
        "price": 70,
        "rating": 4.5,
        "placeType": "room",
        "propertyType": "Apartment",
        "beds": 5,
        "bedrooms": 3,
        "bathrooms": 4,
        "guestCapacity": 15,
        "featureCategory": "Surfing"
    },
    {
        "imgSrc": "https://i.ibb.co/YkXDXGY/view22.webp",
        "location": "Athina, Greece",
        "checkIn": new Date("2023-09-18"),
        "checkOut": new Date("2023-09-19"),
        "locationDecs": "6,629 kilometers away",
        "price": 75,
        "rating": 4.5,
        "placeType": "room",
        "propertyType": "Apartment",
        "beds": 4,
        "bedrooms": 5,
        "bathrooms": 8,
        "guestCapacity": 15,
        "featureCategory": "Surfing"
    },
    {
        "imgSrc": "https://i.ibb.co/28Xhw6T/view23.webp",
        "location": "Marrakesh, Morocco",
        "checkIn": new Date("2023-09-19"),
        "checkOut": new Date("2023-09-21"),
        "locationDecs": "9,594 kilometers away",
        "price": 80,
        "rating": 4.5,
        "placeType": "room",
        "propertyType": "Apartment",
        "beds": 6,
        "bedrooms": 7,
        "bathrooms": 5,
        "guestCapacity": 15,
        "featureCategory": "Surfing"
    },
    {
        "imgSrc": "https://i.ibb.co/3Mkjp69/view24.webp",
        "location": "Carlton, Australia",
        "checkIn": new Date("2023-09-18"),
        "checkOut": new Date("2023-09-22"),
        "locationDecs": "8,688 kilometers away",
        "price": 85,
        "rating": 4.5,
        "placeType": "room",
        "propertyType": "Apartment",
        "beds": 7,
        "bedrooms": 6,
        "bathrooms": 5,
        "guestCapacity": 15,
        "featureCategory": "Farms"
    },
    {
        "imgSrc": "https://i.ibb.co/P6SFW96/view25.webp",
        "location": "Sydney, Australia",
        "checkIn": new Date("2023-09-20"),
        "checkOut": new Date("2023-09-22"),
        "locationDecs": "8,858 kilometers away",
        "price": 90,
        "rating": 4.5,
        "placeType": "room",
        "propertyType": "Guesthouse",
        "beds": 6,
        "bedrooms": 5,
        "bathrooms": 6,
        "guestCapacity": 15,
        "featureCategory": "Farms"
    },
    {
        "imgSrc": "https://i.ibb.co/PcrQZwW/view26.webp",
        "location": "Seoul, South Korea",
        "checkIn": new Date("2023-09-23"),
        "checkOut": new Date("2023-09-24"),
        "locationDecs": "3,750 kilometers away",
        "price": 100,
        "rating": 4.5,
        "placeType": "room",
        "propertyType": "Guesthouse",
        "beds": 5,
        "bedrooms": 6,
        "bathrooms": 5,
        "guestCapacity": 15,
        "featureCategory": "Farms"
    },
    {
        "imgSrc": "https://i.ibb.co/VgPwG4b/view27.webp",
        "location": "Mumbai, India",
        "checkIn": new Date("2023-09-24"),
        "checkOut": new Date("2023-09-26"),
        "locationDecs": "2,007 kilometers away",
        "price": 110,
        "rating": 4.5,
        "placeType": "room",
        "propertyType": "Guesthouse",
        "beds": 8,
        "bedrooms": 7,
        "bathrooms": 6,
        "guestCapacity": 15,
        "featureCategory": "Farms"
    },
    {
        "imgSrc": "https://i.ibb.co/T8STpzt/view28.webp",
        "location": "Ubud, Indonesia",
        "checkIn": new Date("2023-09-26"),
        "checkOut": new Date("2023-09-28"),
        "locationDecs": "4,277 kilometers away",
        "price": 120,
        "rating": 4.5,
        "placeType": "room",
        "propertyType": "Guesthouse",
        "beds": 7,
        "bedrooms": 4,
        "bathrooms": 7,
        "guestCapacity": 15,
        "featureCategory": "Farms"
    },
    {
        "imgSrc": "https://i.ibb.co/qW5Hnp6/view29.webp",
        "location": "Rome, Italy",
        "checkIn": new Date("2023-09-25"),
        "checkOut": new Date("2023-09-27"),
        "locationDecs": "7,522 kilometers away",
        "price": 125,
        "rating": 4.5,
        "placeType": "entire room",
        "propertyType": "Guesthouse",
        "beds": 6,
        "bedrooms": 6,
        "bathrooms": 6,
        "guestCapacity": 15,
        "featureCategory": "Top of the world"
    },
    {
        "imgSrc": "https://i.ibb.co/0Krj9GB/view30.webp",
        "location": "Lisbon, Portugal",
        "checkIn": new Date("2023-09-28"),
        "checkOut": new Date("2023-09-29"),
        "locationDecs": "9,367 kilometers away",
        "price": 115,
        "rating": 4.5,
        "placeType": "entire room",
        "propertyType": "Guesthouse",
        "beds": 5,
        "bedrooms": 5,
        "bathrooms": 5,
        "guestCapacity": 15,
        "featureCategory": "Top of the world"
    },
    {
        "imgSrc": "https://i.ibb.co/hCWkk8p/view3.jpg",
        "location": "Melbourne, Australia",
        "checkIn": new Date("2023-09-28"),
        "checkOut": new Date("2023-09-30"),
        "locationDecs": "8,688 kilometers away",
        "price": 130,
        "rating": 4.5,
        "placeType": "entire room",
        "propertyType": "Hotel",
        "beds": 6,
        "bedrooms": 6,
        "bathrooms": 6,
        "guestCapacity": 15,
        "featureCategory": "Top of the world"
    },
    {
        "imgSrc": "https://i.ibb.co/zscZYSp/view2.jpg",
        "location": "Kuala Lumpur, Malaysia",
        "checkIn": new Date("2023-09-05"),
        "checkOut": new Date("2023-09-08"),
        "locationDecs": "2,383 kilometers away",
        "price": 105,
        "rating": 4.5,
        "placeType": "entire room",
        "propertyType": "Hotel",
        "beds": 7,
        "bedrooms": 7,
        "bathrooms": 7,
        "guestCapacity": 15,
        "featureCategory": "Top of the world"
    },
    {
        "imgSrc": "https://i.ibb.co/3vGCLD3/view1.webp",
        "location": "Rome, Italy",
        "checkIn": new Date("2023-09-10"),
        "checkOut": new Date("2023-09-14"),
        "locationDecs": "7,517 kilometers away",
        "price": 135,
        "rating": 4.5,
        "placeType": "entire room",
        "propertyType": "Hotel",
        "beds": 5,
        "bedrooms": 5,
        "bathrooms": 5,
        "guestCapacity": 15,
        "featureCategory": "Top of the world"
    },
    {
        "imgSrc": "https://i.ibb.co/02hMSTP/view4.webp",
        "location": "Paris, France",
        "checkIn": new Date("2023-09-15"),
        "checkOut": new Date("2023-09-20"),
        "locationDecs": "8,126 kilometers away",
        "price": 145,
        "rating": 4.5,
        "placeType": "entire room",
        "propertyType": "Hotel",
        "beds": 8,
        "bedrooms": 8,
        "bathrooms": 8,
        "guestCapacity": 15,
        "featureCategory": "Amazing"
    },
    {
        "imgSrc": "https://i.ibb.co/qWNB7Hj/view5.webp",
        "location": "London, UK",
        "checkIn": new Date("2023-09-20"),
        "checkOut": new Date("2023-09-25"),
        "locationDecs": "8,205 kilometers away",
        "price": 140,
        "rating": 4.5,
        "placeType": "entire room",
        "propertyType": "Hotel",
        "beds": 8,
        "bedrooms": 8,
        "bathrooms": 8,
        "guestCapacity": 15,
        "featureCategory": "Amazing"
    },
    {
        "imgSrc": "https://i.ibb.co/V2PN6kd/view6.webp",
        "location": "Split, Croatia",
        "checkIn": new Date("2023-09-25"),
        "checkOut": new Date("2023-09-30"),
        "locationDecs": "7,170 kilometers away",
        "price": 35,
        "rating": 4.5,
        "placeType": "entire room",
        "propertyType": "Hotel",
        "beds": 7,
        "bedrooms": 7,
        "bathrooms": 7,
        "guestCapacity": 15,
        "featureCategory": "Amazing"
    },
    {
        "imgSrc": "https://i.ibb.co/dGY7824/view7.webp",
        "location": "Bondi Beach, Australia",
        "checkIn": new Date("2023-09-12"),
        "checkOut": new Date("2023-09-16"),
        "locationDecs": "8,864 kilometers away",
        "price": 45,
        "rating": 4.5,
        "placeType": "entire room",
        "propertyType": "Hotel",
        "beds": 6,
        "bedrooms": 6,
        "bathrooms": 6,
        "guestCapacity": 15,
        "featureCategory": "Amazing"
    },
    {
        "imgSrc": "https://i.ibb.co/ZG7wQxn/view8.webp",
        "location": "Cape Town, South Africa",
        "checkIn": new Date("2023-09-16"),
        "checkOut": new Date("2023-09-21"),
        "locationDecs": "9,963 kilometers away",
        "price": 55,
        "rating": 4.5,
        "placeType": "entire room",
        "propertyType": "Hotel",
        "beds": 5,
        "bedrooms": 5,
        "bathrooms": 5,
        "guestCapacity": 15,
        "featureCategory": "Amazing"
    }
]